# Generated by Django 4.2.5 on 2023-12-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0002_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="imagen",
            field=models.FileField(blank=True, null=True, upload_to="media/avatares"),
        ),
    ]
