# Generated by Django 4.2.5 on 2023-12-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0004_post_perfil_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="epigrafe",
            field=models.CharField(default="texto por defecto", max_length=30),
            preserve_default=False,
        ),
    ]
